/*
 * generated by Xtext
 */
package com.holycityaudio.spincadmenu;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SpinCADMenuUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return com.holycityaudio.spincadmenu.ui.internal.SpinCADMenuActivator.getInstance().getInjector("com.holycityaudio.spincadmenu.SpinCADMenu");
	}

}
