/*
 * generated by Xtext
 */
package com.holycityaudio.spincad.serializer;

import com.google.inject.Inject;
import com.holycityaudio.spincad.services.SpinCADGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class SpinCADSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SpinCADGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Skip___VerticalLineKeyword_2_0_IDTerminalRuleCall_2_1__a;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SpinCADGrammarAccess) access;
		match_Skip___VerticalLineKeyword_2_0_IDTerminalRuleCall_2_1__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getSkipAccess().getVerticalLineKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getSkipAccess().getIDTerminalRuleCall_2_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getIDRule())
			return getIDToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	 */
	protected String getIDToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Skip___VerticalLineKeyword_2_0_IDTerminalRuleCall_2_1__a.equals(syntax))
				emit_Skip___VerticalLineKeyword_2_0_IDTerminalRuleCall_2_1__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('|' ID)*
	 *
	 * This ambiguous syntax occurs at:
	 *     flags=ID (ambiguity) ',' label=[Label|ID]
	 */
	protected void emit_Skip___VerticalLineKeyword_2_0_IDTerminalRuleCall_2_1__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
